name: Action di Eftimie
on:
  push:
jobs:
  bunasearabarosane: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Buna seara, Barosane!"
      - run: echo "Se vede din departare"
      - run: echo "Ca ai bani in buzunare"
      - run: echo "Hai sa ne traiesti, Patroane!"
      - run: python --version
      - run: pip --version
      - run: ifconfig
      - run: lsb_release -a
      - run: pwd
      - run: env
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            eftimie
      - run: ls -la
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7' 
      - run: pip install -r eftimie/requirements.txt
      - run: python model_script.py
        working-directory: eftimie
      - uses: actions/upload-artifact@v4
        with:
          name: model-outputs
          path: eftimie/outputs