name: Action di Eftimie
on:
  push:
jobs:
  bunasearabarosane: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Buna seara, Barosane!"
      - run: echo "Se vede din departare"
      - run: echo "Ca ai bani in buzunare"
      - run: echo "Hai sa ne traiesti, Patroane!"
  Manipulation:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
      - run: pip --version
      - run: ifconfig
      - run: lsb_release -a
      - run: ls -la
      - run: pwd
      - run: env 