name: Action di Eftimie

on:
  push:

jobs:
  bunasearabarosane: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Buna seara, Barosane!"
      - run: echo "Se vede din departare"
      - run: echo "Ca ai bani in buzunare"
      - run: echo "Hai sa ne traiesti, Patroane!"
      - run: python --version
      - run: pip --version
      - run: ifconfig
      - run: lsb_release -a
      - run: pwd
      - run: env

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            eftimie

      - run: ls -la

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7' 

      - name: Install dependencies
        run: pip install -r eftimie/requirements.txt

      - name: Train model
        run: python inizio.py
        working-directory: eftimie

      - name: Upload outputs (model + risultati)
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: eftimie/outputs

      - name: Run Flask inference test with pytest
        run: pytest
        working-directory: eftimie